version: '3.8'

services:
  app:
    build: .
    networks:
      - custom_network
    ports:
      - "5051:5051"
    environment:
      DATABASE_URL: 'mysql://root:password@db:3306/ecommerce'
    depends_on:
      - db
    command: npm run start
    volumes:
      - .:/app 
      - /app/node_modules

  db:
    image: mysql:8
    networks:
      - custom_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - custom_network
    ports:
      - 8080:8080

networks:
  custom_network:
    driver: bridge
    
volumes:
  mysql_data:
